name: Hello Composite Action
description: A simple composite action

inputs:
  enviornment:
    description: 'Environment name'

runs:
  using: composite
  steps:    
    - name: Step 1
      run: echo "Hello from composite action step 1"
      shell: bash
    
    - name: Step 2
      run: |
        echo "Environment inside composite action: ${{ inputs.enviornment }}"
      shell: bash
