name: Caller Workflow 1
on:
  workflow_dispatch:
jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/resuable-intro.yaml
    with:
      # You can pass inputs to the reusable workflow here if needed
      enviornment: "Dev"
      enable-logging: true
      replicas: 3

    # secrets:
    #   REPO_SECRET: ${{ secrets.REPO_SECRET }} ##explicitly passing the secret
    secrets: inherit ##inheriting all applicable secrets from the caller workflow

  # This job will run after the reusable workflow job and will use the output from it
  use-deployment-name:
    needs: call-reusable-workflow
    runs-on: ubuntu-latest
    steps:
      - name: Use deployment name from reusable workflow
        run: |
          echo "Deployment Name from reusable workflow: ${{ needs.call-reusable-workflow.outputs.deployment-name }}"