name: Caller Workflow 1
on:
  workflow_dispatch:
jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/resuable-intro.yaml
    with:
      # You can pass inputs to the reusable workflow here if needed
      enviornment: "Dev"
      enable-logging: true
      replicas: 3