name: Reusable Workflow Intro
on:
  workflow_call:
    inputs:
      enviornment:
        description: 'Enviornment name'
        required: true #workflow will fail if this input is not provided
        type: string
        default: 'Dev'. #if not provided, default value will be used
      enable-logging:
        description: 'Enable logging'
        required: true
        type: boolean
        # default: 'false'
      replicas:
        description: 'Number of replicas'
        required: true
        type: number
        # default: '1'

    secrets:
      MY_SECRET:
        description: 'A secret value'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print parameters
        run: |
          echo "Hello from the reusable workflow!"
          echo "Environment: ${{ inputs.enviornment }}"
          echo "Enable Logging: ${{ inputs.enable-logging }}"
          echo "Replicas: ${{ inputs.replicas }}"
      
      - name: Use secret
        run: |
          echo "Using secret value: ${{ secrets.MY_SECRET }}"
