name: Runner Lab

on:
  workflow_dispatch:

jobs:
  job-1:
    runs-on: ubuntu-latest

    steps:
      - name: Create file
        run: |
          echo "Created by Job 1" > demo.txt

      - name: Read file in another step
        run: cat demo.txt

  job-2:
    needs: job-1
    runs-on: ubuntu-latest

    steps:
      - name: Try reading Job 1 file. #jobs runs in different runners, so this will fail
        run: cat demo.txt.            #they share no file system, so the file created in job-1 is not available in job-2