name: Environment Secrets and Variables

on:
  workflow_dispatch:

jobs:
  Wrokflow-env:
    name: Print Workflow Env Values
    runs-on: ubuntu-latest

    steps:
      - name: Print Workflow variables  #these are defined ar repo level in Settings → Secrets and variables → Actions → Variables
        run: |
          echo "Region: ${{ vars.Region }}"

  dev:
    runs-on: ubuntu-latest

    # This job gets secrets and variables from DEV environment
    environment: dev

    steps:
      - name: Print Dev  Env Values
        run: |
          echo "Environment Name: ${{ vars.ENV_NAME }}"
          echo "Secret: ${{ secrets.ENV_SECRET_KEY }}"


  qa:
    runs-on: ubuntu-latest

    # This job gets secrets and variables from QA environment
    environment: qa

    steps:
      - name: Print QA  Env Values
        run: |
          echo "Environment Name: ${{ vars.ENV_NAME }}"
          echo "Secret: ${{ secrets.ENV_SECRET_KEY }}"