name: testing
on:
  workflow_dispatch:
jobs:
  test:
    uses: Deepakj25/Deepakj25/.github/workflows/blank.yml@v1
    with:
        enviornment: "Dev"
        enable-logging: true
        replicas: 3
    secrets:
        REPO_SECRET: ${{ secrets.REPO_SECRET }}
